import pandas as pd
import numpy as np
import joblib
import json
import os

# --- Configuration ---
# Set N_TRIALS to 500 for faster execution
N_TRIALS = 500  

# Mission parameters for a high-stakes, representative mission
MISSION_PARAMS = {
    'launch_vehicle': 'GSLV Mk III',
    'launch_window': 'Morning',
    'mission_type': 'Communication',
    'launch_site': 'Satish Dhawan Space Centre',
    'payload_weight_kg': 3500,
    'temperature_C': 27.0,
    'wind_speed_kmh': 12.0,
    'humidity_percent': 70.0,
    'system_health_index': 0.98,
    'vehicle_success_rate': 0.93  # GSLV Mk III historical rate
}

# Financial parameters (in millions of USD)
COST_OF_LAUNCH = 100.0  # Cost to build and launch (excluding payload)
PAYLOAD_REVENUE = 500.0 # Revenue generated by the successful payload (e.g., satellite value)
FAILURE_LOSS_PENALTY = 50.0 # Contractual or reputation loss penalty on failure

# --- Setup ---
data_file = 'data/isro_300_missions.csv'
model_file = 'launch_model_pipeline.pkl'
output_file = 'mc_results.json'

if not os.path.exists(data_file):
    print(f"Error: Data file '{data_file}' not found. Please check your data directory.")
    exit()
if not os.path.exists(model_file):
    print(f"Error: Model file '{model_file}' not found. Please run main.py to train the model.")
    exit()

# Load Model Pipeline
try:
    model = joblib.load(model_file)
except Exception as e:
    print(f"Error loading model: {e}")
    exit()

# Create a representative input DataFrame for prediction
input_df = pd.DataFrame([MISSION_PARAMS])

# --- 1. Get Predicted Success Probability ---
try:
    predicted_success_prob = model.predict_proba(input_df)[0][1]
    print(f"Predicted Success Probability for scenario: {predicted_success_prob:.4f}")
except Exception as e:
    print(f"Error during prediction: {e}")
    exit()

# --- 2. Monte Carlo Simulation ---
results = []

for _ in range(N_TRIALS):
    is_successful = np.random.rand() < predicted_success_prob
    
    net_value = -COST_OF_LAUNCH # Initial cost of launch
    
    if is_successful:
        net_value += PAYLOAD_REVENUE
    else:
        net_value -= FAILURE_LOSS_PENALTY
        
    results.append(net_value)

results = np.array(results)

# --- 3. Calculate Key Metrics ---
simulated_success_rate = np.mean(results > -COST_OF_LAUNCH) 
expected_net_value = np.mean(results)
value_at_risk = np.percentile(results, 5)

# --- 4. Strategic Insight Generation ---
if expected_net_value > 0 and value_at_risk > -150:
    risk_insight = "The expected value is positive, and the 95% Value-at-Risk is within an acceptable range, suggesting high financial viability."
elif expected_net_value > 0 and value_at_risk < -150:
    risk_insight = "While the expected value is positive, the Value-at-Risk is significant. A small chance of catastrophic loss exists, requiring robust insurance."
else:
    risk_insight = "The mission carries a high financial risk, with a negative expected net value. Strategic review of costs or revenue is recommended before proceeding."

# --- 5. Save Results ---
mc_data = {
    'simulated_success_rate': simulated_success_rate,
    'expected_net_value_M': round(expected_net_value, 2),
    'value_at_risk_M': round(value_at_risk, 2),
    'risk_insight': risk_insight,
    'n_trials': N_TRIALS
}

with open(output_file, 'w') as f:
    json.dump(mc_data, f, indent=4)

print("\n--- Monte Carlo Simulation Complete ---")
print(f"Trials: {N_TRIALS}")
print(f"Results saved to {output_file}")
